### ISSUE TITLE
markdownfmt-format-buffer: Could not locate executable "markdownfmt"

### ISSUE THREAD

**Issue by basille** [nlamirault/emacs-markdownfmt#7]
Hi,

Trying to use `markdownfmt` with Emacs 28.2 under Debian (bookworm). Install through MELPA went fine, but it seems the package cannot find the executable "markdownfmt". If I run `markdownfmt-format-buffer`, I get the error message:

```
Could not locate executable "markdownfmt"
```

I then tried installing it following the instructions [here](https://github.com/shurcooL/markdownfmt), but it did not change anything.

Anything I'm missing? Thanks!

**Comment by jn64** [comment]
> I then tried installing it following the instructions [here](https://github.com/shurcooL/markdownfmt), but it did not change anything.

Assuming you did `go install ...`, that installs to `$GOPATH`, which is likely not in your `$PATH` unless you've previously set it up.

Two possible solutions:

1) Set the full `/path/to/markdownfmt` in the variable `markdownfmt-bin`

2) Or, put something like this near the end of your `~/.bashrc`, to make `markdownfmt` available in your shell:

```
export GOPATH="$HOME/go"
export PATH="$PATH:$GOPATH/bin"
```

References:
- [Docs for `go install`](https://pkg.go.dev/cmd/go#hdr-Compile_and_install_packages_and_dependencies)
- [Docs for go environment variables](https://pkg.go.dev/cmd/go#hdr-Environment_variables)

**Comment by basille** [comment]
Thank you so much @jn64! It did work by installing `markdownfmt` in `/usr/local/bin/`, just as you explained, and Emacs can now find it.

Problem fixed!
